---
- name: Update system
  ansible.builtin.yum:
    update_cahe: yes

- name: Ensure Apache is installed
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Start and enable Apache service 
  ansible.builtin.service: 
    name: httpd
    state: started 
    enabled: yes 

- name: Create a Directory for the Website
  ansible.builtin.file:
    path: "/var/www/{{ your_domain }}"
    state: directory
    mode: '0755'
    recurse: yes

- name: Copy custom index.html
  ansible.builtin.copy:
    src: index.html
    dest: "/var/www/{{ your_domain }}/index.html"
    mode: '0644'