---
- name: Configure apache on Debian OS
  import_tasks: apache_on_debian.yml
  when: ansible_os_family == "Debian"
  tags: ubuntu

- name: Configure apache on Fedora OS
  ansible.builtin.yum:
    update_cache: yes
  when: ansible_os_family == "RedHat"
  tags: centos