---
- name: Create Prometheus group
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    state: present
    
- name: Create Prometheus user
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    shell: /sbin/nologin

- name: Create Prometheus Data Directory
  ansible.builtin.file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    recurse: yes

- name: Create Prometheus config directory
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    recurse: yes

- name: Create Prometheus Temp Driectory
  ansible.builtin.file:
    path: "{{ prometheus_temp_dir }}"
    state: directory

- name: Download Prometheus
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "{{ prometheus_temp_dir }}"
    remote_src: yes

- name: Copy prometheus and promtool binary to the install Directory
  ansible.builtin.copy:
    src: "{{ prometheus_temp_dir }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_install_dir }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    remote_src: yes
  with_items: 
    - prometheus
    - promtool

- name:  Move consoles and console_libraries to /etc/prometheus
  ansible.builtin.copy:
    src: "{{ prometheus_temp_dir }}/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_config_dir }}"
    remote_src: yes
  with_items: 
    - console_libraries  
    - consoles