--- 
- name: Install Java
  ansible.builtin.yum:
    name: "{{ java_package }}"
    state: present

- name: Create Tomcat group
  ansible.builtin.group:
    name: tomcat
    state: present

- name: Create Tomcat user
  ansible.builtin.user:
    name: tomcat
    group: tomcat
    home: "{{ tomcat_install_dir }}"
    createhome: no
    shell: /bin/nologin
    state: present

- name: Download Tomcat
  ansible.builtin.get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

- name: Create Tomcat installation directory
  ansible.builtin.file:
    path: "{{ tomcat_install_dir }}"
    state: directory
    owner: tomcat
    group: tomcat

- name: Extract Tomcat archive
  ansible.builtin.unarchive:
    src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: tomcat
    group: tomcat

- name: Create Tomcat service file
  ansible.builtin.template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify: Reload systemd

- name: Start and enable Tomcat service
  ansible.builtin.systemd:
    name: tomcat
    state: started
    enabled: yes

- name: Open firewall port for Tomcat
  ansible.builtin.firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
  notify: Reload firewall